### ISSUE TITLE
compile error, missing parameter -lnvidia-ml

### ISSUE THREAD

**Issue by OliverLeitner** [al42and/cuda-smi#1]
i think theres a problem with your Makefile.

heres the error im getting:

g++ -I/usr/local/cuda//include -L/usr/local/cuda//lib64/ cuda-smi.cpp -lnvidia-ml -lcudart_static -lpthread -ldl -lrt -o cuda-smi
/usr/bin/ld: cannot find -lnvidia-ml
collect2: error: ld returned 1 exit status
make: **\* [cuda-smi] Fehler 1

some sys specs:

cuda toolkit version 7.0 from nvidia.com resides in /usr/local/cuda
cuda management library newest installed in global scope (as of 30-5-2015)
g++ version (Ubuntu 4.8.2-19ubuntu1) 4.8.2
sys Description: Ubuntu 14.04.2 LTS
nvidia module version: nvidia-349, 349.16, 4.0.1, x86_64: installed

hope youre able to help me out.
greetings
Oliver

**Comment by al42and** [comment]
Hi Oliver,

Do you have the file `libnvidia-ml.so` in `/usr/lib/x86_64-linux-gnu/` directory (or probably somewhere else)? If you don't, then try reinstalling the driver.

If you do, you can either add `-L/usr/lib/x86_64-linux-gnu/` to `g++` options in Makefile, or do this globally by creating the file `/etc/ld.so.conf.d/nvidia-driver-libs.conf` with content like

```
/usr/lib/x86_64-linux-gnu
```

and then run `sudo ldconfig`. (If `libnvidia-ml.so` resides in some other directory on your system, use it instead).

Hope that helps!

**Comment by OliverLeitner** [comment]
hi al42and

after i added the -L param and point it to my version of libnvidia-ml.so (in my case one of three possible places was /usr/lib/nvidia-$modversion/) everything worked out fine.

i guess thats the standard path with ubuntu for that library.
